language: cpp

compiler:
    - clang
    - gcc

os: linux

before_install:
    # g++ 4.9
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

      # clang 3.4
    - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

    - sudo apt-get update -qq

install:
    # g++ 4.8
    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.9; fi
    - if [ "$CXX" == "g++" ]; then export CXX="g++-4.9"; fi

    # clang 3.5
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.6; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.6"; fi

    # Required libraries
    - sudo apt-get install libcairo2-dev libpango1.0-dev libglib2.0-dev libimlib2-dev libgtk2.0-dev libxinerama-dev libx11-dev libxdamage-dev libxcomposite-dev libxrender-dev libxrandr-dev librsvg2-dev libstartup-notification0-dev

before_script:
    - mkdir "${TRAVIS_BUILD_DIR}/build"
    - cd "${TRAVIS_BUILD_DIR}/build"
    - cmake "${TRAVIS_BUILD_DIR}" -DCMAKE_BUILD_TYPE=Release

script:
    - cd "${TRAVIS_BUILD_DIR}/build"
    - make all test
