sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

os: linux

before_install:
  # g++ 4.9
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

install:
  # g++ 4.8
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.9"; fi

  # CMake 3.2
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.2-Linux-x86_64.sh -O /tmp/cmake_install.sh
  - sudo mkdir -p /opt/cmake
  - sudo sh /tmp/cmake_install.sh --exclude-subdir --prefix=/opt/cmake
  - export PATH="/opt/cmake/bin:${PATH}"
  - cmake --version

  # Required libraries
  - sudo apt-get --assume-yes install libcairo2-dev libpango1.0-dev libglib2.0-dev libimlib2-dev libgtk2.0-dev libxinerama-dev libx11-dev libxdamage-dev libxcomposite-dev libxrender-dev libxrandr-dev librsvg2-dev libstartup-notification0-dev

before_script:
  - mkdir "${TRAVIS_BUILD_DIR}/build"
  - cd "${TRAVIS_BUILD_DIR}/build"
  - cmake "${TRAVIS_BUILD_DIR}" -DCMAKE_BUILD_TYPE=Release

script:
  # Verify tint3 builds and passes tests
  - cd "${TRAVIS_BUILD_DIR}/build"
  - make all test

  # Verify the installation script works, then clean up
  - sudo make install DESTDIR=/opt/tint3 && sudo rm -rf /opt/tint3
